update extension to newest version
Azure/azure-batch-cli-extensions pull request #139
Opened 2022-08-31 00:27 UTC by wiboris

Updating the batch cli to the latest python sdk versions.
updating samples

2022-08-31 14:10 UTC, dpwatrous requested changes

2022-08-31 23:08 UTC, wiboris commented on batch-cli-extensions/azext_batch/_params.py
> -        c.argument('application_package_references', nargs='+', validator=validate_pool_settings)
there still there, inherited

2022-08-31 23:29 UTC, wiboris commented on batch-cli-extensions/azext_batch/_params.py
> +        c.extra('targets',
This is how it appears to the user in help, its the same as in the regular cli version

Pool: Virtual Machine Configuration: Disk Encryption Configuration Arguments
    --targets                         : If omitted, no disks on the compute nodes in the pool will
                                        be encrypted. On Linux pool, only "TemporaryDisk" is
                                        supported; on Windows pool, "OsDisk" and "TemporaryDisk"
                                        must be specified. Space seperated target disks to be
                                        encrypted. Values can either be OsDisk or TemporaryDisk.

Pool: Virtual Machine Configuration: Node Placement Configuration Arguments
    --policy                          : Node placement Policy type on Batch Pools. Allocation policy
                                        used by Batch Service to provision the nodes. If not
                                        specified, Batch will use the regional policy.  Allowed
                                        values: regional, zonal.

2022-08-31 23:33 UTC, wiboris commented on batch-cli-extensions/azext_batch/_params.py
> +        c.argument('id', arg_group='Job')
It was there as a param to the custom method but was not being exposed to the user in help

2022-09-01 00:35 UTC, wiboris commented on batch-cli-extensions/azext_batch/custom.py
> +        if allow_task_preemption:
updated

2022-09-01 00:36 UTC, wiboris commented on batch-cli-extensions/azext_batch/custom.py
>                      if disk_encryption_targets:
changed the variable names

2022-09-01 00:37 UTC, wiboris commented on batch-cli-extensions/azext_batch/custom.py
> +                certificate_references=None, application_package_references=None, metadata=None, targets=None,
changed the variable names

2022-09-06 21:43 UTC, dpwatrous requested changes

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +                line = line.replace(search_result.group(1), Key_REPLACEMENT)
If we're going to print out the cassettes we scrubbed secrets from, these should be included.

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +            else:
This one's minor, but removing the nested if statement would make this read a lot clearer. I stared at it for an embarrassingly long time before I noticed the nested `t.write(line)`.

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
>      print('Bearer tokens removed from the following cassettes:')
How about just 'Secrets scrubbed from the following cassettes:'

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +    print('All cassettes free from Bearer and Shared Key tokens!')
Again, I think just saying 'secrets' instead of enumerating what was scrubbed would be better.

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +                linex = search_result.group(1)
These "linex" vars are unused

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +Key_REPLACEMENT = '"fakeKey"'
Nit: Constants should be all caps

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +SIG_PATTERN = r'sig=(.+?)\\'
I don't think it matters in practice, but this is replacing the entire storage URL after `sig=`, and ends up looking like `sig=sig=fakeSig`

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +SIG_PATTERN = r'sig=(.+?)\\'
Here's a pattern that should just match the signature value (stolen from our CLI scrubber): `r'\?sv=.*&(sig=[^&]+)&'`

2022-09-06 21:43 UTC, dpwatrous commented on batch-cli-extensions/azext_batch/_params.py
> -        c.argument('application_package_references', nargs='+', validator=validate_pool_settings)
I'm not sure why this validator was defined on application_package_references specifically, but it looks like validate_pool_settings is no longer called anywhere.

2022-09-06 21:43 UTC, dpwatrous commented on scripts/scrub_vcr_auth.py
> +Key_REPLACEMENT = '"fakeKey"'
This replacement results in invalid YAML due to an unescaped quote.
<img width="483" alt="Screen Shot 2022-09-06 at 5 43 18 PM" src="https://user-images.githubusercontent.com/509299/188746288-a8485a74-9000-45ca-b813-7460d19e609b.png">

2022-09-07 21:11 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +                line = line.replace(search_result.group(1), Key_REPLACEMENT)
included

2022-09-07 21:13 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +            else:
cleaned it up a bit

2022-09-07 21:13 UTC, wiboris commented on scripts/scrub_vcr_auth.py
>      print('Bearer tokens removed from the following cassettes:')
changed

2022-09-07 21:13 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +    print('All cassettes free from Bearer and Shared Key tokens!')
changed

2022-09-07 21:14 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +                linex = search_result.group(1)
removed

2022-09-07 21:14 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +Key_REPLACEMENT = '"fakeKey"'
changed

2022-09-07 22:48 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +SIG_PATTERN = r'sig=(.+?)\\'
I update the code but I couldn't seem to use the regex expression, it didn't match.

2022-09-07 22:48 UTC, wiboris commented on batch-cli-extensions/azext_batch/_params.py
> -        c.argument('application_package_references', nargs='+', validator=validate_pool_settings)
removed

2022-09-07 22:49 UTC, wiboris commented on scripts/scrub_vcr_auth.py
> +Key_REPLACEMENT = '"fakeKey"'
fixed

2022-09-09 19:36 UTC, dpwatrous approved these changes
Changes look good to me!

2022-09-09 20:05 UTC, merged